### PR TITLE
Fix white page

### PR DESCRIPTION
**Pull request by n4j1Br4ch1D**
**SOLVED** **FIXED**
i was getting a white page .
i went to index.php 
and set define('ENVIRONMENT', 'development');
i got two errors:
 1-Severity: Notice  --> Only variable references should be returned by reference C:\xampp\htdocs\exclusiveunlock\system\core\Common.php 257
2-Fatal error: Uncaught Error: Call to undefined function mysql_pconnect()

### CODE REVIEW

**Comment by XIT07** [comment]
**Thanks man  (solved Done)**

**Comment by imanthaashan77** [comment]
> **Thanks man (solved Done)**

i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303
my script not work , help me

**Comment by imanthaashan77** [comment]
> **SOLVED** **FIXED**
> i was getting a white page .
> i went to index.php
> and set define('ENVIRONMENT', 'development');
> i got two errors:
> 1-Severity: Notice --> Only variable references should be returned by reference C:\xampp\htdocs\exclusiveunlock\system\core\Common.php 257
> 2-Fatal error: Uncaught Error: Call to undefined function mysql_pconnect()

i have same error . can i contact you   please write my whatsapp    +94712556303    https://wa.me/94712556303
my script not work , help me

**Comment by imanthaashan77** [comment]
> **Thanks man (solved Done)**

i need your contact number sir      +9471255303   https://wa.me/94712556303   my whatsapp numer

**Comment by imanthaashan77** [comment]
> **SOLVED** **FIXED**
> i was getting a white page .
> i went to index.php
> and set define('ENVIRONMENT', 'development');
> i got two errors:
> 1-Severity: Notice --> Only variable references should be returned by reference C:\xampp\htdocs\exclusiveunlock\system\core\Common.php 257
> 2-Fatal error: Uncaught Error: Call to undefined function mysql_pconnect()

i need your contact number sir +9471255303 https://wa.me/94712556303 my whatsapp numer

**Comment by n4j1Br4ch1D** [comment]
> > **SOLVED** **FIXED**
> > i was getting a white page .
> > i went to index.php
> > and set define('ENVIRONMENT', 'development');
> > i got two errors:
> > 1-Severity: Notice --> Only variable references should be returned by reference C:\xampp\htdocs\exclusiveunlock\system\core\Common.php 257
> > 2-Fatal error: Uncaught Error: Call to undefined function mysql_pconnect()
> 
> i have same error . can i contact you please write my whatsapp +94712556303 https://wa.me/94712556303
> my script not work , help me
solution is here:
https://github.com/n4j1Br4ch1D/exclusiveunlock/tree/fix-white-page

**Comment by imanthaashan77** [comment]
sir need whatsapp number.................can you connect my pc via teamvier and serup

**Comment by imanthaashan77** [comment]
> > > **SOLVED** **FIXED**
> > > i was getting a white page .
> > > i went to index.php
> > > and set define('ENVIRONMENT', 'development');
> > > i got two errors:
> > > 1-Severity: Notice --> Only variable references should be returned by reference C:\xampp\htdocs\exclusiveunlock\system\core\Common.php 257
> > > 2-Fatal error: Uncaught Error: Call to undefined function mysql_pconnect()
> > 
> > 
> > i have same error . can i contact you please write my whatsapp +94712556303 https://wa.me/94712556303
> > my script not work , help me
> > solution is here:
> > https://github.com/n4j1Br4ch1D/exclusiveunlock/tree/fix-white-page

can connect my pc via teamviwer   can you write my whatsapp to chatting and do this work

**Comment by dasturuztv** [comment]
nothing happened to me either. pelase help me whatsapp +998977245353

**Pull request merged**
